# The URL the site will be built for
base_url = "https://meanstoasend.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "clean"

taxonomies = [
  {name = "categories", rss = true, paginate_by=5},
  {name = "tags", rss = true, paginate_by=5},
]

title = "Means to a Send, LLC"
description = "App developin' and rally drivin'"
highlight_code = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

author = "richo"
clean_blog_menu = [
{url = "$BASE_URL", name = "Home"},
{url = "$BASE_URL/about", name = "About"},
{url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
  {url = "https://instagram.com/richo_butts", icon="fab fa-instagram"},
  {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
